<!DOCTYPE html>
<html lang="en">
<head>
	<title>Internet Speeds by Country Map</title>
	<link rel="canonical" href="https://www.fastmetrics.com/internet-connection-speed-by-country.php" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="robots" content="noindex, nofollow"/>
	<link rel="shortcut icon" href="https://www.fastmetrics.com/assets/images/fmicon.ico"/>
	<link rel="apple-touch-icon" href="https://www.fastmetrics.com/assets/images/touch-icon-iphone.png">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!--[if lt IE 9]><script src="https://www.fastmetrics.com/assets/js/css3-mediaqueries.js"></script><![endif]-->
	<!--[if lt IE 9]><script src="https://www.fastmetrics.com/assets/js/html5shiv.js"></script><![endif]-->
	<link href="https://www.fastmetrics.com/assets/css/main.css" rel="stylesheet" >
</head>
<body class="page">
	
	<div id="countries-map"></div>
	<p>Source: <a target="_blank" href="https://www.fastmetrics.com/internet-connection-speed-by-country.php">Fastmetrics</a></p>

	<script defer src="https://www.fastmetrics.com/assets/js/jquery.min.js"></script>
    <script defer src="https://www.fastmetrics.com/assets/js/bootstrap.min.js"></script>
	<script defer src="https://www.fastmetrics.com/assets/js/jquery.validate.js"></script>
	<script defer src="https://www.fastmetrics.com/assets/js/slick.min.js"></script>
	<script defer src="https://www.fastmetrics.com/assets/js/main.js"></script>

	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<script type="text/javascript">
		google.charts.load('current', {'packages':['geochart']});
		google.charts.setOnLoadCallback(drawRegionsMap);
		function drawRegionsMap() {
			var data = google.visualization.arrayToDataTable([
				['Country', 'Average Internet Speed (Mbps)'],
				['Andorra', 13.7],
				['United Arab Emirates', 6.9],
				['Afghanistan', 1.1],
				['Antigua and Barbuda', 2.1],
				['Anguilla', 5.0],
				['Albania', 5.8],
				['Armenia', 3.9],
				['Angola', 2.1],
				['Antarctica', 11.3],
				['Argentina', 4.7],
				['American Samoa', 1.3],
				['Austria', 12.3],
				['Australia', 8.2],
				['Aruba', 6.2],
				['Azerbaidjan', 3.6],
				['Bosnia-Herzegovina', 6.9],
				['Barbados', 6.1],
				['Bangladesh', 2.7],
				['Belgium', 14.2],
				['Burkina Faso', 0.6],
				['Bulgaria', 13.3],
				['Bahrain', 4.4],
				['Burundi', 3.6],
				['Benin', 1.1],
				['Bermuda', 5.2],
				['Brunei Darussalam', 4.1],
				['Bolivia', 2.0],
				['Brazil', 4.1],
				['Bahamas', 8.2],
				['Bhutan', 2.4],
				['Bouvet Island', 1.4],
				['Botswana', 2.4],
				['Belarus', 6.9],
				['Belize', 2.1],
				['Canada', 13.1],
				['Cocos (Keeling) Islands', 1.0],
				['Central African Republic', 0.9],
				['CD', 1.0],
				['Congo', 1.0],
				['Switzerland', 16.7],
				['CI', 2.1],
				['Cook Islands', 2.7],
				['Chile', 6.1],
				['Cameroon', 1.7],
				['China', 4.1],
				['Colombia', 4.5],
				['Costa Rica', 3.4],
				['Former Czechoslovakia', 1.6],
				['Serbia', 8.5],
				['Cuba', 4.5],
				['Cape Verde', 6.4],
				['Christmas Island', 2.7],
				['Cyprus', 6.7],
				['Czech Republic', 15.9],
				['Germany', 12.9],
				['Djibouti', 1.8],
				['Denmark', 16.1],
				['Dominica', 11.9],
				['Dominican Republic', 2.8],
				['Algeria', 2.1],
				['Ecuador', 4.4],
				['Estonia', 11.0],
				['Egypt', 1.7],
				['Eritrea', 1.1],
				['Spain', 12.1],
				['Ethiopia', 2.2],
				['Finland', 16.6],
				['Fiji', 5.2],
				['Falkland Islands', 0.9],
				['Micronesia', 0.9],
				['Faroe Islands', 8.2],
				['France', 8.9],
				['Gabon', 1.7],
				['Great Britain', 13.9],
				['Grenada', 5.6],
				['Georgia', 8.4],
				['French Guyana', 3.4],
				['Ghana', 1.8],
				['Gibraltar', 8.7],
				['Greenland', 3.7],
				['Gambia', 1.6],
				['Guinea', 1.1],
				['Guadeloupe (French)', 4.3],
				['Equatorial Guinea', 1.3],
				['Greece', 7.3],
				['S. Georgia & S. Sandwich Isls.', 6.5],
				['Guatemala', 3.1],
				['Guam (USA)', 6.4],
				['Guinea Bissau', 0.6],
				['Guyana', 2.7],
				['Hong Kong', 16.8],
				['Honduras', 2.7],
				['Croatia', 6.4],
				['Haiti', 2.4],
				['Hungary', 12.6],
				['Indonesia', 3.9],
				['Ireland', 12.8],
				['Israel', 11.6],
				['India', 2.8],
				['British Indian Ocean Territory', 0.7],
				['Iraq', 3.7],
				['Iran', 2.0],
				['Iceland', 15.4],
				['Italy', 7.4],
				['Jamaica', 6.0],
				['Jordan', 3.3],
				['Japan', 17.4],
				['Kenya', 5.0],
				['Kyrgyzstan', 3.0],
				['Cambodia', 4.4],
				['Kiribati', 6.8],
				['Comoros', 0.9],
				['Saint Kitts & Nevis Anguilla', 4.5],
				['North Korea', 2.0],
				['South Korea', 26.7],
				['Kuwait', 4.6],
				['Cayman Islands', 6.2],
				['Kazakhstan', 6.4],
				['Laos', 2.4],
				['Lebanon', 1.8],
				['Saint Lucia', 3.2],
				['Liechtenstein', 11.3],
				['Sri Lanka', 4.8],
				['Liberia', 2.9],
				['Lesotho', 3.1],
				['Lithuania', 14.3],
				['Luxembourg', 9.9],
				['Latvia', 16.7],
				['Libya', 0.7],
				['Morocco', 3.7],
				['Monaco', 12.6],
				['Moldavia', 11.1],
				['Madagascar', 3.3],
				['Marshall Islands', 2.3],
				['Macedonia', 6.9],
				['Mali', 0.5],
				['Myanmar', 2.8],
				['Mongolia', 7.9],
				['Macau', 10.1],
				['Northern Mariana Islands', 2.2],
				['Martinique (French)', 5.2],
				['Mauritania', 1.2],
				['Montserrat', 6.9],
				['Malta', 11.8],
				['Mauritius', 3.5],
				['Maldives', 3.2],
				['Malawi', 1.7],
				['Mexico', 5.9],
				['Malaysia', 5.2],
				['Mozambique', 2.1],
				['Namibia', 2.0],
				['New Caledonia (French)', 4.8],
				['Niger', 0.8],
				['Norfolk Island', 1.7],
				['Nigeria', 2.7],
				['Nicaragua', 2.8],
				['Netherlands', 17.0],
				['Norway', 18.8],
				['Svalbard and Jan Mayen', 18.8],
				['Nepal', 2.0],
				['Nauru', 1.4],
				['Niue', 1.5],
				['New Zealand', 9.3],
				['Oman', 3.1],
				['Panama', 3.8],
				['Peru', 4.5],
				['Polynesia (French)', 1.9],
				['Papua New Guinea', 3.5],
				['Philippines', 3.2],
				['Pakistan', 2.1],
				['Poland', 11.0],
				['Saint Pierre and Miquelon', 6.9],
				['Pitcairn Island', 2.9],
				['Puerto Rico', 9.4],
				['Portugal', 12.1],
				['Palau', 2.2],
				['Paraguay', 1.6],
				['Qatar', 6.7],
				['Reunion (French)', 5.9],
				['Romania', 13.2],
				['Russia', 11.6],
				['Rwanda', 9.9],
				['Saudi Arabia', 3.4],
				['Solomon Islands', 0.7],
				['Seychelles', 2.9],
				['Sudan', 1.2],
				['SS', 1.2],
				['Sweden', 19.1],
				['Singapore', 13.9],
				['Saint Helena', 1.4],
				['Slovenia', 12.4],
				['Svalbard and Jan Mayen Islands', 2.7],
				['Slovakia', 12.5],
				['Sierra Leone', 2.0],
				['San Marino', 6.6],
				['Senegal', 1.8],
				['Somalia', 1.7],
				['Suriname', 2.4],
				['Saint Tome (Sao Tome) and Principe', 2.3],
				['Former USSR', 3.4],
				['El Salvador', 2.9],
				['Syria', 1.2],
				['Swaziland', 1.4],
				['Turks and Caicos Islands', 5.4],
				['Chad', 1.2],
				['Togo', 0.8],
				['Thailand', 9.3],
				['Tadjikistan', 3.9],
				['Tokelau', 4.8],
				['Turkmenistan', 2.5],
				['Tunisia', 3.1],
				['Tonga', 2.0],
				['Turkey', 6.3],
				['Trinidad and Tobago', 7.5],
				['Tuvalu', 1.8],
				['Taiwan', 12.9],
				['Tanzania', 2.2],
				['Ukraine', 11.2],
				['Uganda', 1.7],
				['United States', 14.2],
				['Uruguay', 6.2],
				['Uzbekistan', 2.5],
				['Vatican City State', 15.7],
				['Saint Vincent & Grenadines', 4.4],
				['Venezuela', 1.6],
				['Virgin Islands (British)', 3.9],
				['Virgin Islands (USA)', 6.1],
				['Vietnam', 3.8],
				['Vanuatu', 1.8],
				['Wallis and Futuna Islands', 4.2],
				['Samoa', 1.9],
				['Yemen', 1.0],
				['Mayotte', 3.3],
				['South Africa', 4.1],
				['Zambia', 1.4],
				['Zimbabwe', 4.0],
				['United Kingdom', 13.0]
			]);
			var options = {
				colorAxis: {colors: ['#ff0000', '#ffff1a', '#77b300']}
			};
			var chart = new google.visualization.GeoChart(document.getElementById('countries-map'));
			chart.draw(data, options);
		}
    </script>
	
	<style>
		#countries-map{width:100%;height:750px;overflow:hidden;}
		@media screen and (max-width:992px){
			#countries-map{height:550px;}
		}
		@media screen and (max-width:420px){
			#countries-map{height:320px;}
		}
	</style>

</body>
</html>