<?php
$title= "Fastmetrics, Inc. ISP - Mobile Apps Privacy Policy";
$desc= "Read the Mobile Apps Privacy Policy and details outlined here by Fastmetrics, Inc.";
$h2 = "Fastmetrics, Inc. Business ISP";
$h1 = "Mobile Apps Privacy Policy";
$share = "";
$chat = "yes";
$banner = "black-iphone-close-up-user-guides-cover";
$banner_alt = "black iphone close up user guides cover";
$robots="noindex, follow";
include("inc/header.php");
?>

<section>
	<article>
		<div class="container_fluid">
			<div class="container">
				<p>Effective: July 1, 2019</p>
				<h2>Introduction</h2>
				<p>Fastmetrics, Inc. and its subsidiaries and other affiliates (“Fastmetrics”) recognizes and supports the privacy rights of all persons, and we respect these rights when we collect and process personal information (“PI”). We have developed and adopted this Privacy Policy to describe our privacy values and guide our processing of personal information. By purchasing, subscribing to, or utilizing the Products and/or Services, or registering to attend, attending and/or participating in any Fastmetrics sponsored events or other events in which Fastmetrics participates, you agree to be bound to the terms and conditions of this Privacy Policy.</p>
				<p>The obligations and responsibilities set out in this Privacy Policy are applicable to Fastmetrics and its personnel and will be made available on Fastmetrics’ website (<a href="https://www.Fastmetrics.com/privacy-policy">www.Fastmetrics.com/privacy-policy</a>).&nbsp; The obligations and responsibilities set out in the Privacy Policy are in addition to any other applicable policies or agreements entered into with Fastmetrics&nbsp; and any applicable laws and/or regulations.</p>
				<h2>General Statement</h2>
				<p>Fastmetrics is dedicated to the use of <a href="https://www.fastmetrics.com/blog/phone-systems/what-is-voip-how-does-it-work/">Voice over Internet Protocol (VoIP)</a> and related technologies to improve the telecommunications industry and the lives of individuals throughout the world.</p>
				<p>Fastmetrics’ goal is to deliver carrier-grade communications services to all its Clients, at a reasonable price and to make available all the benefits that VoIP offers as broadly as possible. In order to achieve this goal, a Privacy Policy is necessary.</p>
				<h2>Scope</h2>
				<p>At Fastmetrics, privacy matters.&nbsp; Fastmetrics respects the privacy of its Clients and other individuals with whom Fastmetrics has business interactions</p>
				<p>This policy is global, applying to all Fastmetrics locations. It applies to personal information regardless of format.&nbsp; For example, the policy applies to computerized records and electronic information as well as paper-based files.</p>
				<p>It is also applicable to all personal information that is collected, maintained or processed by Fastmetrics. The concepts enumerated in this policy will guide Fastmetrics’ selection and expectations of its Clients, partners, agents and/or contractors to whom Fastmetrics transfers and relies on for processing of personal information.</p>
				<p>Fastmetrics provides the technology platform for hosted or “cloud” <a href="https://www.fastmetrics.com/metricvoice">unified communications as a service offerings (UCaaS)</a>. These Products merely act as a conduit for data transmitted by third parties and Subscribers.&nbsp; Fastmetrics processes personal information that is controlled by or originated from other companies, such as our Clients or other business partners. Fastmetrics also processes personal information in the course of providing support for Fastmetrics communications products. Fastmetrics shall protect the personal information, comply with all laws that regulate the processing of such personal information, and process the information only as authorized by the data controller or the data subject. Accordingly, Fastmetrics relies on guidance and direction of the Client (as the data controller), who determines the purposes of processing such personal information.&nbsp; In some cases, Fastmetrics may collect and process personal information for our own business purposes and shall comply with the applicable privacy laws concerning Fastmetrics processing.</p>
				<p>While Fastmetrics does process data in its role of providing a technology platform, it does not own, control or direct the use of any of the personal information stored or processed by any Client or Subscriber.&nbsp; Fastmetrics only processes such personal information in order to provide and invoice for purchased and/or subscribed Products and Services.</p>
				<h2>Data Processor</h2>
				<p>Fastmetrics provides the technology platform for hosted or “cloud” unified communications as a service offerings (<a href="https://www.fastmetrics.com/blog/tech/ucaas-15-benefits/">UCaaS</a>). These Products merely act as a conduit for data transmitted by third parties and Subscribers. Fastmetrics processes personal information that is controlled by or originated from other companies, such as our Clients or other business partners. Fastmetrics also processes personal information in the course of providing support for Fastmetrics communications products.</p>
				<p>Fastmetrics shall protect the personal information, comply with all laws that regulate the processing of such personal information, and process the information only as authorized by the data controller or the data subject. Accordingly, and in its role as a data processor, Fastmetrics relies on guidance and direction of the Client (as the data controller), who determines the purposes of processing such personal information. In some cases, Fastmetrics&nbsp; may collect and process personal information for our own business purposes and shall comply with the applicable privacy laws concerning Fastmetrics processing.</p>
				<p>While Fastmetrics does process data in its role of providing a technology platform, it does not own, control or direct the use of any of the personal information stored or processed by any Client or Subscriber. Fastmetrics only processes such personal information in order to provide and invoice for purchased and/or subscribed Products and Services.</p>
				<h2>What Information We Collect or Process</h2>
				<p>Fastmetrics processes and in certain situations collects personal information as needed to deliver its Products and Services and manage its business.&nbsp; When collecting personal information, Fastmetrics does so in a reasonable and lawful manner.</p>
				<p>The types of information and the purposes for which Fastmetrics collects or processes personal information may include:</p>
				<h3>Indirect End User Phone Contact Information (Personal Identifiable Information)</h3>
				<p>Fastmetrics acts as a data processor with regard to indirect end user personal identifiable information and our Clients act as the data controller of such data. In the course of Fastmetrics’ processing and protection of such data, all use will be in conformity with the data controller’s instructions.</p>
				<p>Specifically, only when enabled via system permission on Fastmetrics Android and Fastmetrics iOS, Fastmetrics shows personal contacts within the respective application. When the user sends an SMS message to one of his/her phone contacts, or when the user initiates a call to one of his/her phone contacts, the phone number is sent securely through Fastmetrics’ API. Fastmetrics does not store this number with any other PII, and it cannot be directly or indirectly attributed to any person or persons; Fastmetrics stores only the phone number and pertinent metadata so as to be compliant with all applicable state and federal laws, and Fastmetrics does not share this data with any advertisers or third parties under any circumstances. A user can revoke phone contact access on his/her mobile device at any time, and his/her app experience is not hindered or interrupted.</p>
				<p>Fastmetrics Android and iOS also uses Gravatar, only when enabled via Settings and UIConfigs, which is a service that provides avatar images linked to the MD5 hash of the user’s email address. This means that, only when Gravatar use is enabled, we hash each contact’s email address and send it to Gravatar to try and retrieve an avatar image. MD5 hashes cannot be directly or indirectly attributed to any person or persons, and we only send the MD5 hash to Gravatar, never the email address in plain text. As with phone contacts, a user can revoke Gravatar access at any time in Settings or via UIConfig, and his/her app experience is not hindered or interrupted.</p>
				<h3>CLIENTS</h3>
				<p>Fastmetrics uses such personal information only for relevant, appropriate, and customary purposes. Fastmetrics will not share or disclose personal information for purposes other than as described herein. Capitalized terms used in this Privacy Policy shall have the meaning as given in Client’s Master Services Agreement (MSA). The following are examples of some of the personal information Fastmetrics may process.</p>
				<h3>Business Contact Information:</h3>
				<p>Fastmetrics may collect and use personal information about individual contacts of Clients and others who access Fastmetrics public websites, knowledge bases, forums, ticket systems, or provide personal information through other means. Such information may include but is not limited to account information, first/last name, company name, title, and responsibilities, work email address, work mailing address, telephone numbers, login information, device identifiers, as well as additional information provided by such individuals in the course of receiving Products and Services from Fastmetrics and/or requesting information about Fastmetrics. We will use such information for the purposes of providing Products and Services, support, conducting data analytics and product assessments and related activities, and providing information regarding Fastmetrics Products and Services.</p>
				<h3>Customer Proprietary Network Information (CPNI):</h3>
				<p>Customer Proprietary Network Information (CPNI) may include information regarding quantity, destination, technical configuration, location, amount of use and related billing information of telecommunications, interconnected and/or non-interconnected Voice over Internet Protocol (VoIP) services.&nbsp;This may include but is not limited to the phone numbers that you call or send messages to (or the phone numbers that you receive these calls and messages from) through our Products and Services.&nbsp;The date, time and duration of the calls may also be collected.&nbsp;This data is used for billing and service level assurance.</p>
				<p>Fastmetrics provides Products and Services that are primarily for the benefit of Clients and Subscribers in that Fastmetrics transmits, routes, switches or caches information. These Products and Services merely act as a conduit for data transmitted by third parties and Subscribers. Fastmetrics does not determine the purposes and means of processing this personal information. Except for Subscriber data provided by the Client (the Subscribers service provider) for which Fastmetrics is merely providing a conduit for transmission, the subscribed services are of such a nature that, in most instances, Fastmetrics requires and collects only essential CPNI and billing information; and opting out or declining to provide the requested data may hinder the provision or delivery of subscribed services. However, for CPNI data that is collected by Fastmetrics that is not subject to the control of others, Fastmetrics shall obtain consent from the user for the processing of this data.</p>
				<p>Fastmetrics collects end-user CPNI in the course of providing Product support. This data may pertain to Clients of Fastmetrics or Subscribers (eg: end users of Fastmetrics’ direct Clients). This data may include IP address, telephone number, email address, call detail records, call recordings and other information sufficient to identify an individual end user.</p>
				<h3>Indirect End User’s CPNI:</h3>
				<p>Fastmetrics acts as a data processor with regard to indirect end user personal information and our Clients act as the data controller of such data. In the course of Fastmetrics’ processing and protection of such data, all use will be in conformity with the data controller’s instructions.</p>
				<h3>Direct End User’s CPNI:</h3>
				<p>Fastmetrics typically collects and processes direct end user (eg: Clients, vendors, and partners) personal information for the purposes of providing Products and Services, support, conducting data analytics and managing product performance.</p>
				<h3>Messaging, Voicemail, Video and Media Files:</h3>
				<p>Fastmetrics provides Products and Services that facilitate the recording and storage of audio and video by way of features such as but not limited to voicemail, call and conference recording.&nbsp; Users may elect to store or record personal information within these resources at their discretion.</p>
				<h3>Anonymized, Non-Identifying Voice and Traffic Data</h3>
				<p>Fastmetrics may use anonymized, non-identifying data collected from use of our metricVOICE and other Fastmetrics Products and Services. This anonymized, non-identifying data may be used to enhance such items, but is not limited to, voice activation, improve traffic analysis algorithms and techniques, and recognition algorithms. This processing is executed under applicable terms and supports Fastmetrics’ legitimate interests in tuning, maintaining and enhancing these Products and Services.</p>
				<h2>How We Collect Information</h2>
				<p>We collect information in various ways, including the following:</p>
				<p>When you use one of our Products or Services, Fastmetrics collects, and stores certain information that you provide directly. We also collect information about your use of the Products and Services.</p>
				<h3>Cookies and Similar Collection Methods</h3>
				<p>Fastmetrics also collects technical information about your usage of the Products and Services, and we use various technologies to collect information about cookies, IP addresses, device type and device identifiers, application state and the date and time of activity with our Products and Services, and other similar information. Fastmetrics may associate this information with your user identification and/or account number for our internal use.</p>
				<h3>Other Passive Site Tracking</h3>
				<p>Websites may also utilize Internet Protocol (IP) addresses and log files to identify network and server concerns and problems. Fastmetrics also utilizes web beacons and other passive tracking mechanisms to perform standard website traffic analysis in a similar manner to how we utilize cookies.</p>
				<h3>Credit Card Information</h3>
				<p>Fastmetrics only collects credit card information in order to bill for purchased or subscribed to Products and Services. Fastmetrics utilizes third-party credit card payment processing agents (where these agents are required to implement reasonable and appropriate measures to protect and secure this information from loss or misuse) solely for the purpose of processing payments for those Products and Services purchased or subscribed to. These payment processors use of your personal information is governed by their privacy policies, as well as adhering to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like American Express, Visa, Mastercard, and Discover.</p>
				<h2>HOW DOES Fastmetrics UTILIZE COOKIES</h2>
				<h3>General Information about Cookies</h3>
				<p>A cookie (also known as an HTTP cookie, web cookie, or browser cookie) is a small piece of data sent from a website and stored in a user’s web browser while the user is browsing that website. Every time the user loads the website, the browser sends the cookie back to the server to notify the website of the user’s previous activity. Cookies were designed to be a reliable mechanism for websites to remember useful information (such as items in a shopping cart) or to record the user’s browsing activity (including clicking particular or specific buttons, logging in or recording which pages were visited by the user as far back as months or years ago).</p>
				<h3>Utilization of Cookies</h3>
				<p>A visit to a page on <a href="https://www.Fastmetrics.com">www.Fastmetrics.com</a> (or other Fastmetrics website) may generate the following types of cookie(s):</p>
				<h3>Anonymous Analytics Cookies</h3>
				<p>Every time a user visits a Fastmetrics website, software provided by another organization (such as Google Analytics) generates an ‘anonymous analytics cookie’. These cookies can tell us whether you have visited the site before. Your browser will inform us if you have these cookies and, if you don’t, our website generates new ones. This allows Fastmetrics to track how many individual users we have and how often they visit the site. Unless you are signed in to <a href="https://Fastmetrics.com">Fastmetrics.com</a> (or any other Fastmetrics website), we cannot use these cookies to identify individuals. We use these cookies to gather statistics: for example, the number of visits to a page. If you are logged in to the Fastmetrics website, we will also be provided the details you gave to us for this, such as but not limited to your username and email address.</p>
				<h2>How Do I Turn Cookies Off</h2>
				<p>It is usually possible to stop your browser accepting cookies, or to stop it accepting cookies from a specific website.&nbsp;Most modern browsers allow you to change your cookie settings. You can usually find these settings in the ‘options’ or ‘preferences’ menu of your browser. To understand these settings, you can use the ‘Help’ option in your browser for more details. It is solely your responsibility to stop cookies in your browser.</p>
				<p>Note: If you block the use of cookies, then this will limit the service that we are able to provide to you and may affect your visitor/user experience.</p>
				<h3>VENDORS, SUPPLIERS AND SUBCONTRACTORS</h3>
				<p>Fastmetrics may collect personal information about individuals who are employed by our suppliers and vendors. This business contact and payment information are strictly used to administer existing and future business arrangements.</p>
				<h3>OTHERS</h3>
				<p>Additional personal information may be collected, processed and disclosed for the purposes for which it was collected and for legal compliance purposes, including regulatory reporting, investigation of allegations of wrongdoing, and the management and defense of legal claims and actions, and compliance with subpoenas, court orders, and other legal obligations.&nbsp;For example, we may collect information about individuals that visit our office or other facilities. When we do collect data, such collection shall be relevant, proportionate and limited to the purposes for which they are processed.</p>
				<h2>How We Use the Information We Collect</h2>
				<p>We use your information primarily and as necessary to provide you with the various Fastmetrics Products and Services, including but not limited to one or more of the following ways: to create your accounts and allow use of our Products, to provide technical support and respond to Client inquiries, to prevent fraud or potentially illegal activities, enforce our other agreements with you, to notify Clients of application updates, and to inform Clients about new products or promotional offers.</p>
				<h3>SENSITIVE INFORMATION</h3>
				<p>Fastmetrics recognizes that for some sensitive information, affirmative express consent from individuals is required and must be obtained if such information is to be (i) disclosed to a third party or (ii) processed for a purpose other than those for which it was originally collected or subsequently authorized by the individuals through the exercise of opt-in choice.&nbsp; In addition, Fastmetrics shall treat as sensitive any personal information received from a third party where the third party identifies and treats it as sensitive.</p>
				<h3>MARKETING MATERIALS</h3>
				<p>If you provide us with your email address or other business contact information to enable us to provide communications and information to you, we may use the information for providing such communications including the delivery of press releases and other Fastmetrics marketing materials. You may request to no longer receive Fastmetrics marketing communications by following the “unsubscribe” instructions in emails from Fastmetrics or by sending a request to the contact identified below.</p>
				<p>In the rare and unlikely event that Fastmetrics wishes to use an individual’s personal information for a purpose that is materially different from the purpose(s) for which it was originally collected or subsequently authorized by the individuals, Fastmetrics will seek consent in advance as required by applicable law.</p>
				<h2>Sharing Your Information</h2>
				<p>We may disclose or report information that individually identifies Clients, Subscribers or devices in certain circumstances, such as:</p>
				<p>(i) if we have a good faith belief that we are required to disclose the information in response to a valid legal process (for example, a court order, search warrant or subpoena, or to defend or respond to legal actions, and as otherwise authorized by law, or in response to lawful requests by public authorities, including to meet national security or law enforcement requirements); (ii) to satisfy applicable laws, (iii) if we believe that the Products and Services are being used in an unauthorized, unlawful or abusive manner, such as to commit a crime, including to report such criminal activity or to exchange information with other companies and organizations for the purposes of fraud protection and credit risk reduction, (iv) if we have a good faith belief that there is an emergency that poses a threat to the health or safety of a person or the general public, (v) in order to protect the rights or property of Fastmetrics, including enforcement of our Intellectual Property Rights and terms of the Agreement(s), and (vi) for all other purposes with your consent. We may also provide your information to third party companies to perform services on our behalf, including but not limited to payment processing, data analysis, message delivery, hosting services, customer service, and marketing.</p>
				<p>If Fastmetrics enters into a merger, acquisition or sale of all or a portion of its assets or business, Client and Subscriber information, including personal information, will also be transferred as part of or in connection with the transaction as per applicable law.</p>
				<h3>INFORMATION DISCLOSURE</h3>
				<h4>Internal Disclosure</h4>
				<p>In general, personal information may be shared within Fastmetrics, where legally permitted for reasonable and appropriate corporate purposes. However, even within Fastmetrics, we restrict access to personal information to those employees, agents, or contractors who need access to carry out their assigned functions.</p>
				<h4>External Disclosure</h4>
				<p>Fastmetrics uses vendors and partners for a variety of business purposes, such as to help us develop, deploy and invoice for the various Products and Services we provide. We share information with those vendors and partners when it is necessary for them to perform work on our behalf. Fastmetrics requires that these vendors and partners protect the customer information we provide to them and limit their use of such information to their respective processing activity. Fastmetrics will only transfer or provide direct access to personal information covered by this policy to third parties that have made a commitment to respect the privacy rights of the data subject; limit processing of personal information to comply with data controller instructions; and provided Fastmetrics contractual assurances that they will provide at least the same level of privacy protection as is required by applicable privacy laws.</p>
				<h2>Security of Your Information</h2>
				<p>We implement security measures we believe are reasonable to protect your information. It is important that you protect and maintain the security of your account and you need to immediately notify us of any unauthorized use of your account. Remember, no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal information, we cannot and do not guarantee its absolute security.</p>
				<h3>Protecting Personal Information</h3>
				<p>To help protect the confidentiality of personal information, Fastmetrics employs security safeguards appropriate to the sensitivity of the information and in accordance with this Privacy Policy.&nbsp; These safeguards include reasonable administrative, technical and physical measures to safeguard the confidentiality and security of personal information against anticipated threats and unauthorized access to personal information. No transfer of your personal information will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information. Additionally, we convey safeguard obligations to our agents who receive personal information from or on behalf of Fastmetrics in the course of their relationship with our organization as described above in the section titled External Disclosure.</p>
				<h2>Transfer of Data</h2>
				<p>Your information, including personal information, may be transferred to, and maintained on, computers, servers or other data storage located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction. If you reside outside the United States and choose to provide information to Fastmetrics, please note that we transfer the data, including personal information, to the United States and process it there.</p>
				<p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
				<h2>Retention of Data</h2>
				<p>Personal information collected by Fastmetrics will be retained for as long as necessary and legally permitted for the purposes for which it was collected, to provide you with Products and Services, enforce our legal agreements and policies and to conduct our legitimate business interests or where otherwise required by law.</p>
				<h2>Data Integrity</h2>
				<p>Fastmetrics employs reasonable means to keep personal information accurate, complete, and current, as needed for the purposes for which it was collected.</p>
				<h2>How to Access and Update Your Information</h2>
				<p>We generally provide individuals with an opportunity to examine their own personal information, confirm the accuracy and completeness of their personal information, and have their personal information updated, if appropriate.</p>
				<p>The ability of an individual to access his or her personal information is not unlimited, however.&nbsp; An individual’s ability to access personal information may be limited, for example, where (i) the burden or expense of providing access would be unreasonable or disproportionate to the risks to the individual’s privacy, (ii) the information should not be disclosed due to legal or security reasons or to protect confidential commercial information; or (iii) providing access would compromise the privacy of another person.</p>
				<p>If you have created a user profile on a portal, you may also access and revise the personal information in your user profile when you log into your account.</p>
				<p>Individuals who wish to access or update their personal information not accessible via a portal should direct such communications to Fastmetrics support: <a href="mailto:support@fastmetrics.com">support@fastmetrics.com</a></p>
				<h2>Third-Party Websites, Plugins or Widgets</h2>
				<p>Fastmetrics websites, Products and/or Services may include social network or other third-party plugins and widgets not operated by us. Accessing these links to other sites is done at your own option and is not part of any Fastmetrics’ offerings. Fastmetrics has no control over and assumes no responsibility for the content, privacy policies or practices of any third-party sites or services.&nbsp; We strongly advise you to review each privacy policy provided at the respective site.</p>
				<h2>Health Insurance Portability and Accountability Act</h2>
				<p>The Health Insurance Portability and Accountability Act of 1996 (“HIPAA”) is United States legislation that provides data privacy and security provisions for safeguarding medical information. Client acknowledges and agrees that unless the Fastmetrics Products and Services description expressly states otherwise, the Products and Services do not comply with the requirements of the Health Insurance Portability and Accountability Act, as amended, and its implemented regulations. Unless the Products and Services description expressly states otherwise, Client agrees that it will not use the Products and Services to create, receive, transmit, maintain, store, use, disclose, or otherwise cause the Products and Services to handle Protected Health Information (“PHI”) as defined under HIPAA. Client retains complete and full responsibility to ensure that the Products and Services are only applied to use-case scenarios where the Products and Services do provide the necessary level of security and privacy protections. CLIENT’S AGREEMENT TO THIS PROVISION IS A MATERIAL CONDITION OF MAKING THE PRODUCTS AND SERVICES AVAILABLE TO CLIENT. In addition to any indemnity requirements in these Terms, Client shall indemnify, defend and hold harmless Company, Company Affiliates and all of the directors, officers, managers, partners, employees, agents, representatives, heirs, successors and assigns of Company and each of Company’s Affiliates against all actions, claims, losses, penalties, fines, assessments, administrative costs, credit protection costs, damages and expenses (including reasonable attorneys’ fees) arising out of Client’s violation of the provisions of this section, caused in whole or in part by any act or omission of Client, or of anyone employed by or acting as a subcontractor, representative or agent of Client.&nbsp; Any limitation on liability set forth in the terms of the Master Services Agreement or any other agreement between Company or its Affiliates and Client shall not apply to Client’s liability under this provision.</p>
				<h2>California Privacy Rights</h2>
				<p>The California Data Protection Act (Cal. Civ. Code §§ 1798.83), also known as S.B. 27 “Shine the Light Law”, applies to a business that owns or retains California residents’ personal information and, requires such business to disclose to its California customers, upon request, the identity of any third parties to whom the business has disclosed personal information within the previous calendar year, along with the type of personal information disclosed, for the third-parties’ direct marketing purposes.</p>
				<p>A business subject to California Business and Professions Code Section 22581 and the Privacy Rights for California Minors in the Digital World Act (Cal. Bus. &amp; Prof. Code §§ 22580-22582) must allow California residents under age 18 who are registered users of online sites, services or applications to request and obtain removal or other forms of anonymization of content or information they have publicly posted. Your request should include a detailed description of the specific content or information to be so removed.</p>
				<p>Our Products and Services do not address anyone under the age of 18 (“Children”). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us. If we become aware that we have collected personal information from children without verification of parental consent, we take steps to remove that information from our servers.</p>
				<p>If you are a California resident and would like to make such a request, email or contact us at: <a href="mailto:support@fastmetrics.com">support@fastmetrics.com</a></p>
				<h2>Changes to Our Privacy Policy</h2>
				<p>Fastmetrics reserves the right to change this Privacy Policy at our discretion subject to business or legal requirements. You are advised to review and check this Privacy Policy from time to time and particularly before you provide personal information to Fastmetrics. Changes to this Privacy Policy are effective when they are posted on this page. By continuing to use our Products and/or Services you are agreeing to be bound by any changes or revisions made to this privacy policy.</p>
				<h2>Contacting Us</h2>
				<p>If you have any questions, comments, or concerns regarding our Privacy Policy or practices, please send an email to <a href="mailto:support@fastmetrics.com">support@fastmetrics.com</a> or write to Fastmetrics at the following address:</p>
				<p>Fastmetrics, Inc.<br>
				PO BOX 77267<br>
				San Francisco CA, 94107</p>
				<p>Click to view our <a href="https://www.fastmetrics.com/usepolicy.php">Acceptable Use Policy</a> and our <a href="https://www.fastmetrics.com/privacypolicy.php">Terms of Service</a>.</p>
			</div>
		</div>
		<div class="container_fluid text-center blue-bg white text-center">
			<div class="container">
				<div class="row text-center">
					<div class="col-sm-8 offset-sm-2">
						<div class="row">
							<div class="col-sm-4">
								<p><img src="https://www.fastmetrics.com/assets/images/email-icon.png" alt="General Questions"></p>
								<p><strong>General Questions?</strong><br>1-800-724-7100<br><a class="white" href="mailto:sales@fastmetrics.com">sales@fastmetrics.com</a></p>
							</div>
							<div class="col-sm-4">
								<p><img src="https://www.fastmetrics.com/assets/images/sales-icon.png" alt="Contact Sales"></p>
								<p><strong>Contact Sales</strong><br>1-800-724-7100<br><a class="white" href="mailto:sales@fastmetrics.com">sales@fastmetrics.com</a></p>
							</div>
							<div class="col-sm-4">
								<p><img src="https://www.fastmetrics.com/assets/images/phone-icon.png" alt="Contact Support"></p>
								<p><strong>Contact Support</strong><br>888-966-3880<br><a class="white" href="mailto:support@fastmetrics.com">support@fastmetrics.com</a></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</article>
</section>

<?php include("inc/footer.php"); ?>

</body>
</html>