<?php
$title="Fastmetrics, Inc. ISP - Terms of Service &amp; Conditions";
$desc="Read the Terms of Service and Conditions of service usage outlined in this agreement by Fastmetrics, Inc.";
$h2="Fastmetrics, Inc. Business ISP";
$h1="Terms of Service";
$share = "";
$chat = "yes";
$robots="noindex, follow";
include("inc/header.php");
?>

<section>
	<article>
		<div class="container_fluid">
			<div class="container">
				<h3>Fastmetrics, Inc. Terms and Conditions of Service</h3>
				<p>This agreement ("Agreement") is between Fastmetrics, Inc. and an end user ("End User") of the Fastmetrics, Inc. VoIP Voice Service. Any Fastmetrics, Inc. services or products ("Services") provided to End User shall be governed by the terms and conditions herein. By activating the Services, End User acknowledges receiving, reading and understanding this Agreement and accepts the terms and conditions herein. End User acknowledges that they are of legal age to enter into this Agreement.</p>
				<p><strong>I. Terms and Conditions</strong></p>
				<p>The terms and conditions stated herein are in lieu of and replace any and all terms and conditions set forth in any documents issued by End User, including, without limitation, purchase orders and specifications. Any additional, different, or conflicting terms and conditions on any such document issues by end user at any time are hereby objected to by Fastmetrics, Inc. and any such documents shall be wholly inapplicable to any sale made or service rendered hereunder and shall not be binding in any way on Fastmetrics, Inc. No waiver or amendment to this contract or these terms and conditions shall be binding on Fastmetrics, Inc. unless made in writing expressly stating that it is such a waiver or amendment and signed by a duly authorized representative of Fastmetrics, Inc.</p>
				<p><strong>II. Term</strong></p>
				<p>The term of this Agreement ("Term") begins on the date that End User purchases Services and continues monthly for the duration of the service period. At the end of the current Term, the Term is automatically renewed unless End User provides Fastmetrics, Inc. prior to the end of the current Term, notification of intention to terminate the service. End User agrees to pay for Services for the duration of the Term. Expiration of the Term does not alleviate End User of responsibility for paying all unpaid, accrued charges due hereunder. For End Users who choose to rent equipment, if the End User chooses to terminate the Services before the end of the current rental term, disconnection fees may apply as set forth in sections 4.2.2 and 4.2.8.</p>
				<p><strong>III. Limitations for 911 Emergency Dialing</strong></p>
				<ol>
					<li>911. End User acknowledges that Fastmetrics, Inc's Services do not support traditional 911 emergency dialing, whereby calls are automatically routed to an emergency 911 operator with the caller address appearing on the operator's computer. Fastmetrics, Inc. does offer limited 911 services, in which end user 911 dialed calls are routed to the nearest Public Safety Answering Point office (PSAP). Typically these calls are answered by the front desk of the PSAP and then routed to an emergency operator at that location. However, some PSAP's will not accept calls in this manner. End-User agrees to notify, as appropriate, any of its users of the Services who may place calls using End-User's phone services. Fastmetrics, Inc. advises End-User to maintain an alternative means of accessing traditional 911 services such as traditional telephone services or cellular phone services.</li>
					<li>Outages due to Electrical, Internet or other General Failures. End-User acknowledges that the Services will not function in the absence of electrical power, access to the Internet or other general failures associated with the VOIP network. End-User acknowledges that the Services will not function if there is an interruption of End-User's broadband or high-speed Internet access service.</li>
					<li>Non-Voice Systems. End-User acknowledges that the Services are not set up to function with out-dialing systems including home security systems, medical monitoring equipment, satellite television systems and some facsimile systems. By consenting to these terms and conditions, End-User waives any claim against Fastmetrics, Inc. for interruption or disruption of such systems by the Services.</li>
				</ol>
				<p><strong>IV. Equipment</strong></p>
				<p>To provide the Services, Fastmetrics, Inc. may provide Equipment to EndUser. All Equipment shipments are F.O.B. "Fastmetrics, Inc.'s facility. "Fastmetrics, Inc.'s liability for delivery shall cease, and title (if applicable) and all risk of loss or damage shall pass to End User upon delivery to carrier. End User will be provided a twelve (12) month manufacturer's warranty from the date of purchase of Equipment or Service. End User shall be required to obtain authorization from Fastmetrics, Inc. to return any Equipment. Fastmetrics, Inc. will provide replacement Equipment only if the Equipment is deemed to be defective and covered under the warranty. Fastmetrics, Inc. will not cover replacement for lost, stolen, mistreated or modified equipment. Equipment returned by End User that is not covered under warranty may be refused by Fastmetrics, Inc., and End User will be responsible to pay return shipping charges.</p>
			    <p><strong>V. Billing, Charges and Payment</strong></p>
				<ol>
					<li>PAYMENT. Upon purchase of the Service, End User must provide Fastmetrics, Inc. with a valid credit card number from an accepted issuer (American Express, Discover, MasterCard or Visa). End User authorizes Fastmetrics, Inc. to charge the credit card number provided by End User ("Credit Card") for all charges arising from End User's use of the Services. End User agrees to notify Fastmetrics, Inc. of any change to the credit card information including, but not limited to, changes in account number, expiration date or billing address. Fastmetrics, Inc. shall not be responsible for any charges made by the Credit Card issuer to End User's Credit Card account for exceeding credit limit, insufficient funds or other reasons. </li>
					<li>CREDIT TERMS. All Services provided to End User and covered by the Agreement shall at all times be subjected to credit approval or review by Fastmetrics, Inc. End User will provide such credit information or assurance as is requested by Fastmetrics, Inc. at any time. Fastmetrics, Inc., in its sole discretion and judgment, may discontinue credit at any time without notice.</li>
					<li>BILLING. Fastmetrics, Inc. will provide End User with a monthly on-line invoice for the Services and bill all charges invoiced to End User's account to the Credit Card. Such charges shall include activation fees, monthly service fees, shipping charges, disconnection fees, equipment charges, toll charges, taxes and any other applicable charges. Monthly service fees are paid in advance of each month's service; toll charges and any other applicable charges are billed at the end of each month's service. Fastmetrics, Inc. reserves the right to charge the Credit Card for toll charges at any time if End User's cumulative toll charges for the current month exceed two hundred and fifty dollars ($250.00). Billing for monthly service fees commences upon purchase of the Services, and the first month's monthly service fee shall be prorated to take into account any partial month that may occur as the result of the date monthly service fees are initiated. Thereafter, billing for monthly phone services will occur in advance of the month the Services are provided, whereas billing for any toll or long-distance charges will occur in arrears.</li>
					<li>LATE/NON-PAYMENT. If any charges for the Services are due but unpaid for any reason including, but not limited to, non-payment or declined Credit Card charges, Fastmetrics, Inc. may suspend or terminate the Services and all accrued charges shall be immediately due. Fastmetrics, Inc. will charge End User interest (1.5% per month) on those charges and a late fee of 10% of the owed balance. If End User fails to pay Fastmetrics, Inc. within 30 days of billing date, Fastmetrics, Inc. has the right to disconnect the Services without notice and/or send to collection. Upon disconnect, End User agrees to immediately pay all amounts owed to Fastmetrics, Inc. Re-establishment of Service fees of $50.00 and a penalty of $25 apply to ALL disconnected accounts. Upon disconnect, a valid credit or debit card will be required to reinstate service. If payment is not made in full within 60 days, Fastmetrics, Inc. has the right to repossess the End User unit to offset monies owed without liability for damage or trespass.</li>
					<li>TAXES. Prices for the Services do not include any customs duties, sales, use, value added, excise, federal, state, local, public utility or other similar taxes. All such taxes shall be paid by End User and will be added to any amounts otherwise charged to End User unless End User provides Fastmetrics, Inc. with an appropriate exemption certificate. If any amounts paid for the Services are refunded by Fastmetrics, Inc., applicable taxes may not be refundable. At the present time, under the terms of "Fastmetrics, Inc.'s Hosted VoIP Service, federal excise taxes are applicable, as are sales taxes on the ATA should End User choose to purchase. </li>
					<li>CREDITS. End User acknowledges and agrees that the Services are provided "as is, where is." Credit allowances are under the sole discretion of Fastmetrics, Inc.</li>
					<li>DISCOUNTS. From time to time in its sole discretion, Fastmetrics, Inc. may offer promotions or discounts of activation or other fees. Any promotion or discount codes must be entered by End User upon purchase of the Services. End User shall not be entitled to a subsequent credit for such promotions or discounts, if not requested at the time of account creation or change of service.</li>
					<li>BILLING DISPUTES. End User must dispute any charges for the Services within thirty (30) days of receipt of the monthly on-line invoice or End User waives any objection.</li>
				</ol>
				<p><strong>VI. Tolls</strong></p>
				<p>A. USF FEES (Effective as of August 1st, 2011). The Federal Communication Commission (FCC) requires all telecommunication providers in the United States to contribute to the Universal Service Fund which supports mechanisms to ensure the delivery of affordable telecommunications service to all Americans including low-income consumers, eligible schools and libraries, and rural health care providers.  Fastmetrics, Inc. has not been billing for USF previously, and will not be billing for past years fees.  However, Fastmetrics, Inc. now finds it necessary to implement a USF surcharge of 18% on all applicable USF-contributable services. This includes VoIP lines, trunks, seats, all long distance calling, and inbound toll free calling.</p>
               <p>Background</p>
               <p>The Federal Communications Commission (FCC) and Congress recognize that telephone service provides a vital link to emergency services, government services and surrounding communities. To help promote telecommunications service nationwide, the FCC, as directed by Congress and with the help of the Universal Service Administrative Company (USAC), administers the federal Universal Service Fund (USF).</p>
               <p>Programs</p>
               <p>Lifeline/Link-Up.</p>
               <p>
                This program provides discounts on monthly service and initial
                telephone installation or activation fees for primary residences to income-eligible
                consumers. For additional information, see our consumer guide.
                High-Cost. This program ensures that consumers in all regions of the nation have
                access to telecommunications services at rates that are affordable and reasonably
                comparable to those in urban areas.
              </p>
              <p>
                Schools and Libraries.
              </p>
              <p>
                This program makes discounts available to eligible schools
                and libraries for eligible telecommunications services, Internet access and internal
                connections so that schools and libraries may have access to affordable
                telecommunications and information services. For additional information, see our
                consumer guide.
              </p>
              <p>
                Rural Health Care.
              </p>
              <p>
                This program helps link health care providers located in rural areas
                to urban medical centers so that patients living in rural America will have access to the
                same advanced diagnostic and other medical services that are enjoyed in urban
                communities. For additional information, see our consumer guides at:
                <a href="http://www.fcc.gov/guides/universal-service-program-rural-health-care-providers"><b>Rural Health Care Providers</b></a> and
                <a href="http://www.fcc.gov/guides/rural-health-care-pilot-program"><b>Rural Health Care Pilot Program</b></a>.
              </p>
              <p>
                Who Pays for Universal Service?
              </p>
              <p>
                All telecommunications service providers and certain other providers of
                telecommunications must contribute to the federal USF based on a percentage of their
                interstate and international end-user telecommunications revenues. These companies
                include wireline phone companies, wireless phone companies, paging service companies
                and Voice over Internet Protocol (VoIP) providers.  Fees may be passed on to end-users
              </p>
              <p>
                B. TOLLS. Every call to or from Equipment using the Services that originates or terminates in the Public Switched Telephone Network ("PSTN") is subject to the then-applicable toll charges that are associated with the Plan. Every call to or from Equipment using the Services that originates or terminates with a SIP service provider that is not affiliated or associated with Fastmetrics, Inc. will also count as PSTN minutes and be subject to the then-applicable toll charges that are associated with the Plan. Domestic long distance calls are billed in six (6) second increments. Calls to a phone number outside the United States and Canada to a non-Fastmetrics, Inc. account or IP partner will be charged at the current rates published on the Fastmetrics, Inc. website. The duration of each call from the US to international destination is to be calculated in six (6) second increments after a thirty (30) second minimum. Calls to Mexico are rounded to the minute.
              </p>

              <p><strong>VII. Telephone Number</strong></p>
              <p>Telephone numbers provided by Fastmetrics, Inc. ("Number") to the End User shall be leased and not sold. End User is not to use the Number with any other device other than the Equipment without the express written permission of Fastmetrics, Inc. Fastmetrics, Inc. reserves the right to change, cancel or move the Number at its sole discretion. If, however, the End User chooses to 'port' their existing phone number into the Fastmetrics, Inc. VoIP service, the End User shall also be able to 'port' the number out of the Fastmetrics, Inc. network upon termination of service if the End User has maintained an account in good standing with Fastmetrics, Inc.</p>

              <p><strong>VIII. Lost, Stolen, Altered or Broken Equipment</strong></p>

              <p>End User shall not modify the Equipment in any way without the express written permission of Fastmetrics, Inc. End User shall not use the Equipment except with the Services provided hereunder. Except as otherwise provided for hereunder, End User is responsible for all lost, stolen or broken Equipment and may be required to purchase a replacement to continue service. Replacement charges will be based on the fair retail price of equipment, plus applicable shipping costs and taxes. End Users who have existing Equipment belonging to Sky Blue Leasing shall pay Sky Blue Leasing for any such lost, stolen or broken Equipment in an amount equal to the retail price of the Equipment. End User shall immediately notify Fastmetrics, Inc. of any lost or stolen Equipment and shall cooperate with Fastmetrics, Inc. in all reasonable aspects to eliminate actual or potential unauthorized use of the Equipment. At Fastmetrics, Inc.'s sole option, failure to report lost or stolen equipment in a timely manner will cause End User to be responsible for all service fees accrued until the time that Fastmetrics, Inc. is informed of the loss or theft and can effect a termination of the Services.</p>

              <p><strong>IX. Prohibited Uses</strong></p>
              <p>Any use of the Services or any other action that causes a disruption in the network integrity of Fastmetrics, Inc. or its vendors, whether directly or indirectly, is strictly prohibited and could result in termination of the Services. End User understands that neither Fastmetrics, Inc. nor its vendors are responsible for the content of the transmissions that may pass through the Internet and/or the Services. End User agrees that it will NOT use the Services in ways that violate laws, infringe the rights of others, or interfere with the users, services, or equipment of the network. End User agrees and represents that it is purchasing the Services and/or the Equipment for its own internal use only, and shall not resell, transfer or make a charge for the Services or the Equipment without the advance express written permission of Fastmetrics, Inc. Use of service shall not include certain activities including, but not limited to, any autodialing, continuous or extensive call forwarding, continuous connectivity, fax broadcast, fax blasting, telemarketing or any other activity that would be inconsistent with residential or small business usage.</p>

              <p><strong>X. Unlimited Minute Usage Plans; Changes to the Agreement, Services or Plan</strong></p>
              <p>Fastmetrics, Inc. reserves the right to review usage of unlimited minute usage plans to ensure that there is no end-user abuse of such plans. End-user agrees to use unlimited minute plans for normal voice calls and will not employ methods or devices to take advantage of unlimited plans by using service excessively or for means not intended by Fastmetrics, Inc. Fastmetrics, Inc. may terminate service immediately if, in its sole discretion, end-user is abusively using the unlimited minute plan. Fastmetrics, Inc. reserves the right to make changes to the terms and conditions of this Agreement, the Services and/or the Plan ("Change of Service"). In the event of a Change of Service, Fastmetrics, Inc. will post to the website currently located at <a href="http://www.fastmetrics.com/hostedbusinessvoice.php"><b>Hosted Business Voice</b></a>. Notice will be considered received by End Users and such changes will become binding to End Users, on the date the changes are posted to the website ("Change Date"), and no additional notice will be required. Fastmetrics, Inc. will post all changes thirty (30) days in advance of the effective date of change. If End User does not send Fastmetrics, Inc. notification of their desire to terminate this agreement or uses the Service after the Change Date, End User is deemed to have accepted and consented to the change of terms and conditions of the Service. If End User does not consent to the change of service and terminates this agreement, End User will be responsible for any sums due hereunder in addition to any applicable Disconnection Fee. End User may request a Plan change at anytime, subject to any applicable change of service fee and additional terms and conditions. In no case will an activation fee be credited after thirty (30) days from the initial purchase of the Services for a Plan change or cancellation. For a Plan change to a plan that requires a purchase of the Equipment, an equipment charge will apply. Fastmetrics, Inc. may decrease prices for the Services or Plans without providing any prior notice to End User.</p>

              <p><strong>XI. Termination</strong></p>
              <p>End User agrees to provide Fastmetrics, Inc. with thirty (30) days notice of termination. End User shall be responsible for the full monthly service fee for the month during which the notice of termination of service is provided to Fastmetrics, Inc. In accordance with section 4.2.8, a disconnection fee may apply. Fastmetrics, Inc. reserves the right, at its sole discretion, to suspend, terminate or change the Services without advanced notice for any reason, including without limitation, misuse of the Services in any way, End User's breach of this Agreement, End User's failure to pay any sum due hereunder, suspected fraud or other activity by End User that adversely affects the Services, Fastmetrics, Inc., "Fastmetrics, Inc.'s network or other End Users' use of the Services. Fastmetrics, Inc. reserves the right to determine, at its sole discretion, what constitutes misuse of the Services and End User agrees that "Fastmetrics, Inc.'s determination is final and binding on End User. Fastmetrics, Inc. may require an activation fee to change or resume a terminated or suspended account.</p>

              <p><strong>XII.Privacy</strong></p>
              <p>Fastmetrics, Inc. utilizes the public Internet and third party networks to provide voice and video communication services. Accordingly, Fastmetrics, Inc. cannot guarantee the security of voice and video communications of End User. Fastmetrics, Inc. is committed to respecting End User's privacy. Once End User chooses to provide personally identifiable information, it will only be used in the context of the End User's relationship with Fastmetrics, Inc. Fastmetrics, Inc. will not sell, rent, or lease End Users' personally identifiable information to others. Unless required by law or subpoena or if End User's prior permission is obtained, Fastmetrics, Inc. will only share the personal data End User provides with other Fastmetrics, Inc. entities and/or business partners that are acting on "Fastmetrics, Inc.'s behalf to complete the activities described herein. Such Fastmetrics, Inc. entities and/or national or international business partners are governed by "Fastmetrics, Inc.'s privacy policies with respect to the use of this data. Upon the appropriate request of a government agency, law enforcement agency, court or as otherwise required by law, Fastmetrics, Inc. may disclose personally identifiable information.</p>

              <p><strong>XIII. Technical Support</strong></p>
              <p>Fastmetrics, Inc. provides technical support to End Users via telephone and email for the Services and the Equipment provided. Support for other applications and uses is not provided or implied.</p>

              <p><strong>XIV. Breach</strong></p>
              <p>In the event of End User's breach of the terms of the Agreement, including without limitation, failure to pay any sum due hereunder, End User shall reimburse Fastmetrics, Inc. for all attorney, court, collection and other costs incurred by Fastmetrics, Inc. in the enforcement of "Fastmetrics, Inc.'s rights hereunder and Fastmetrics, Inc. may keep any deposits or other payments made by End User.</p>

              <p><strong>XV. Indemnification</strong></p>
              <p> End User agrees to defend, indemnify and hold Fastmetrics, Inc., its affiliates and its vendors harmless from any claims or damages relating to this Agreement.</p>

              <p><strong>XVI. Disclaimer or Consequential Damages</strong></p>
              <p> In no event shall Fastmetrics, Inc. or its vendors be liable for any special, incidental, indirect, punitive or consequential damages or for any damages, including but not limited to loss of data, loss of revenue or profits, or arising out of or in connection with the use or inability to use services or products provided hereunder whether due to a breach of contract, breach of warranty, the negligence of Fastmetrics, Inc. or its vendors or otherwise.</p>

              <p><strong>XVII. Warranty and Liability Limitations</strong></p>
              <p>Fastmetrics, Inc. makes no warranties, express or implied, including, but not limited to, and implied warranties of merchantability or fitness for a particular purpose. Neither Fastmetrics, Inc. nor its vendors will be liable for unauthorized access to "Fastmetrics, Inc.'s or end user's transmission facilities or premise equipment or for unauthorized access to or alteration, theft or destruction of end user's data files, programs, procedures or information through accident, fraudulent means or devices, or and other method, regardless of whether such damage occurs as a result of "Fastmetrics, Inc.'s or its vendors' negligence. Any claim against Fastmetrics, Inc. must be made within 90 days of the event of the claim and Fastmetrics, Inc. has no liability thereafter. "Fastmetrics, Inc.'s liability is limited to repair, replacement, credit or refund. Fastmetrics, Inc. may elect to provide a refund in lieu of credit, replacement or repair. All warranties cover only defects arising under normal use and do not include malfunctions or failures resulting from misuse, abuse, neglect, alteration, modification, improper installation, or repairs by anyone other than Fastmetrics, Inc. In no event shall "Fastmetrics, Inc.'s total liability hereunder exceed the amounts paid by the end user to Fastmetrics, Inc. in the prior twelve (12) months from the date of claim.</p>

              <p><strong>XVIII. Export Compliance</strong></p>
              <p>End User agrees to comply with U. S. Export laws concerning the transmission of technical data and other regulated materials via the Services. End User agrees to comply with applicable local, state and federal regulations governing the locality in which the Equipment and Services are used.</p>

              <p><strong>XIX. Phone Numbers and Web Portal Discontinuance</strong></p>
              <p>Upon expiration, cancellation or termination of the Services, End User shall relinquish and discontinue use of any Numbers, voice mail access numbers and/or web portals assigned to End User by Fastmetrics, Inc. or its vendors.</p>

				  <p><strong>XX. Software Copyright</strong></p>
              <p>Any software used by Fastmetrics, Inc. to provide the Services and any software provided to End User in conjunction with providing the Services are protected by copyright law and international treaty provisions. End User may not copy the software or any portion of it.</p>

              <p><strong>XXI. Survival</strong></p>
              <p>The provisions of section 4, 5, 14, 15, 16, 17 and 21 shall survive any termination of the Agreement.</p>

              <p><strong>XXII. Notices</strong></p>
              <p>Fastmetrics, Inc. communicates with End Users primarily via email. Notices to End User shall be sent to the email address specified by End User at the time of registration for the Services or as subsequently specified by End User ("Email Address"). End User is responsible for notifying Fastmetrics, Inc. of any Email Address changes. End User agrees that sending a message to the Email Address is the agreed upon means of providing notification. Email is used to communicate important information about the Services, billing, changes to the Services and other information. The information is time-sensitive in nature. It is required that End User read any email sent to the Email Address in a timely manner in order to avoid any potential interruption in the Services provided hereunder.</p>

              <p><strong>XXIII. Force majeure (Events Beyond our Control)</strong></p>
              <p>Fastmetrics, Inc. shall not be liable for any delay in performance directly or indirectly caused by or resulting from acts of God, fire, flood, accident, riot, war, government intervention, embargoes, strikes, labor difficulties, equipment failure, late delivery by suppliers or other difficulties of Fastmetrics, Inc. as may occur in spite of "Fastmetrics, Inc.'s best efforts.</p>

              <p><strong>XXIV. Governing Law / Resolution of Disputes</strong></p>
              <p>Mandatory Arbitration. Any dispute or claim between End User and Fastmetrics, Inc. arising out of or relating to the Service or Equipment provided in connection with this Agreement shall be resolved by arbitration before a single arbitrator administered by the American Arbitration Association in accordance with its Commercial Arbitration Rules . The arbitration shall take place in San Francisco County, California and shall be conducted in English. The arbitrator's decision shall follow the plain meaning of the relevant documents, and shall be final and binding. Without limiting the foregoing, the parties agree that no arbitrator has the authority to: (i) award relief in excess of what this Agreement provides; or (ii) award punitive or exemplary damages. Judgment on the award rendered by the arbitrators may be entered in any court having jurisdiction thereof. All claims shall be arbitrated individually and Customer will not bring, or join any class action of any kind in court or in arbitration or seek to consolidate or bring previously consolidated claims in arbitration. Customer acknowledges that this arbitration provision constitutes a waiver of any right to a jury trial. b. Governing Law. The Agreement and the relationship between you and Fastmetrics, Inc. shall be governed by the laws of the State of California without regard to its conflict of law provisions. To the extent court action is initiated to enforce an arbitration award or for any other reason consistent with Section 25.1, End User and Fastmetrics, Inc. agree to submit to the personal and exclusive jurisdiction of the courts located within the state of California, to the extent possible in San Francisco County, and waive any objection as to venue or inconvenient forum. The failure of Fastmetrics, Inc. to exercise or enforce any right or provision of the Agreement shall not constitute a waiver of such right or provision. If any provision of the Agreement is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Agreement remain in full force and effect. End User agrees that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or the Agreement must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>

              <p><strong>XXV. Entire Agreement</strong></p>
              <p> The terms and conditions of this Agreement constitute the entire agreement with regard to this sale and expressly supersede and replace any prior or contemporaneous agreements, written or oral, relating to the Services. This agreement shall be binding upon the heirs, successors, and assigns of Fastmetrics, Inc. and End User. </p>
			</div>
		</div>
	</article>
</section>

<?php include("inc/footer.php"); ?>

</body>
</html>